import type { FormField } from "./types";

export const LESSON_PLAN_SECTIONS = [
  { id: "header", title: "Ταυτότητα σχεδίου μαθήματος" },
  { id: "topic", title: "Θέμα μαθήματος" },
  { id: "identity", title: "1. Ταυτότητα σχεδίου μαθήματος" },
  { id: "rationale", title: "2. Σκεπτικό σχεδίου μαθήματος" },
  { id: "prerequisites", title: "3. Προαπαιτούμενες γνώσεις & επιθυμητές δεξιότητες" },
  { id: "objectives", title: "4. Σκοπός & μαθησιακά αποτελέσματα" },
  { id: "organization", title: "5. Οργάνωση διδασκαλίας & υλικοτεχνική υποδομή" },
  { id: "approach", title: "6. Διδακτική προσέγγιση" },
  { id: "path", title: "7. Αναλυτική περιγραφή διδακτικής πορείας" },
  { id: "extensions", title: "8. Πιθανές επεκτάσεις" },
  { id: "bibliography", title: "9. Βιβλιογραφία – Δικτυογραφία" },
  { id: "appendix", title: "10. Παράρτημα" },
] as const;

export const LESSON_PLAN_FIELDS: FormField[] = [
  { id: "school", label: "Σχολείο", type: "text", section: "header" },
  { id: "class", label: "Τάξη", type: "text", section: "header" },
  { id: "lessonNumber", label: "Α/Α Μαθήματος", type: "text", section: "header" },
  { id: "teacherName", label: "Όνομα Εκπαιδευτικού", type: "text", section: "header" },
  { id: "studentCount", label: "Αριθμός Μαθητών", type: "text", section: "header" },
  { id: "teachingUnit", label: "Διδακτική Ενότητα", type: "text", section: "header" },
  { id: "teachingPeriod", label: "Διδακτική Περίοδος", type: "text", section: "header" },
  { id: "teachingHour", label: "Διδακτική Ώρα", type: "text", section: "header" },
  { id: "thematicField", label: "Θεματικό Πεδίο", type: "text", section: "header" },
  {
    id: "topic",
    label: "Θέμα",
    type: "text",
    section: "topic",
    placeholder: "π.χ. Η έννοια της δύναμης, 2 σημαντικές δυνάμεις στη φύση",
  },
  {
    id: "topicSubtitle",
    label: "Υπότιτλος (προαιρετικό)",
    type: "text",
    section: "topic",
    placeholder: "π.χ. (The Overhand Tennis Serve)",
  },
  {
    id: "planTitle",
    label: "Τίτλος σχεδίου μαθήματος",
    type: "text",
    section: "identity",
  },
  {
    id: "gradeLevel",
    label: "Βαθμίδα - Τάξη",
    type: "text",
    section: "identity",
    placeholder: "π.χ. Γυμνάσιο – Β' Γυμνασίου",
  },
  {
    id: "cognitiveAreas",
    label: "Εμπλεκόμενες γνωστικές περιοχές και συμβατότητα με ΠΣ",
    type: "textarea",
    section: "identity",
    rows: 3,
  },
  {
    id: "studentOutcomes",
    label: "Ο/Η μαθητής/τρια να είναι σε θέση",
    type: "textarea",
    section: "identity",
    placeholder: "Ένας στόχος ανά γραμμή",
    rows: 6,
  },
  {
    id: "curriculumReference",
    label: "Αναφορά Αναλυτικού Προγράμματος Σπουδών",
    type: "textarea",
    section: "identity",
    rows: 2,
  },
  {
    id: "duration",
    label: "Χρονική διάρκεια",
    type: "text",
    section: "identity",
    placeholder: "π.χ. Δύο - τρεις διδακτικές ώρες",
  },
  {
    id: "rationale",
    label: "Σκεπτικό (και πιθανές αντιλήψεις μαθητών/τριών)",
    type: "textarea",
    section: "rationale",
    rows: 6,
  },
  {
    id: "prerequisites",
    label: "Προαπαιτούμενη γνώση & επιθυμητές δεξιότητες",
    type: "textarea",
    section: "prerequisites",
    placeholder: "Μία γραμμή ανά δεξιότητα ή γνώση",
    rows: 6,
  },
  {
    id: "learningObjectives",
    label: "Μαθησιακοί στόχοι - Αποτελέσματα",
    type: "textarea",
    section: "objectives",
    placeholder: "Ένας στόχος ανά γραμμή",
    rows: 6,
  },
  {
    id: "facilities",
    label: "Αθλητικές εγκαταστάσεις / Χώρος διεξαγωγής",
    type: "textarea",
    section: "organization",
    rows: 2,
  },
  {
    id: "equipment",
    label: "Όργανα / Εξοπλισμός",
    type: "textarea",
    section: "organization",
    rows: 2,
  },
  {
    id: "classOrganization",
    label: "Οργάνωση τάξης",
    type: "textarea",
    section: "organization",
    rows: 4,
  },
  {
    id: "organization",
    label: "Οργάνωση της διδασκαλίας & απαιτούμενη υλικοτεχνική υποδομή",
    type: "textarea",
    section: "organization",
    rows: 6,
  },
  {
    id: "teachingApproach",
    label: "Μέθοδος διδασκαλίας - Διδακτική προσέγγιση",
    type: "textarea",
    section: "approach",
    rows: 6,
  },
  {
    id: "teachingPath",
    label: "Αναλυτική περιγραφή διδακτικής πορείας",
    type: "textarea",
    section: "path",
    rows: 10,
  },
  {
    id: "extensions",
    label: "Πιθανές επεκτάσεις - προσαρμογές σχεδίου μαθήματος",
    type: "textarea",
    section: "extensions",
    rows: 4,
  },
  {
    id: "bibliography",
    label: "Βιβλιογραφία – Δικτυογραφία",
    type: "textarea",
    section: "bibliography",
    rows: 6,
  },
  {
    id: "appendix",
    label: "Παράρτημα",
    type: "textarea",
    section: "appendix",
    rows: 8,
  },
];
